const ACTION_TYPES = {
  FETCH_INVENTORY: 'FETCH_INVENTORY',
  FETCH_INVENTORY_SUCCESS: 'FETCH_INVENTORY_SUCCESS',
  FETCH_INVENTORY_FAILURE: 'FETCH_INVENTORY_FAILURE',

  SET_FILTER: 'SET_FILTER',

  CHANGE_PAGE: 'CHANGE_PAGE',
};

export default ACTION_TYPES;
